name: test SSH command

on: push

jobs:
  directory-update:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd public_html
            var=“$(date + “%m-%d-%Y_%H%M”)”
            mkdir test-github-deploy-$var
            mv glassroom-test/. test-github-deploy-$var
          host: ${{ secrets.HOST }}
          username: xeghpcmy
          password: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
