name: test SSH command

on: push

jobs:
  directory-update:
    runs-on: ubuntu-latest

    steps:
      - name: Move Files
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd public_html \
            mkdir glassroom_archive/test-github-deploy-$(date "+%m-%d-%Y_%H%M") \
            mv glassroom-test/* glassroom_archive/test-2-github-deploy-$(date "+%m-%d-%Y_%H%M")
          host: ${{ secrets.HOST }}
          username: xeghpcmy
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
